spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:musinsadb
    username: user
    password:

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  messages:
    encoding: UTF-8
  sql:
    init:
      encoding: utf-8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
