--
-- MEMBER INFO
--
DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER COMMENT '회원' (
    MEMBER_NO       INT             NOT NULL    AUTO_INCREMENT      COMMENT '회원 번호',
    MEMBER_ID       VARCHAR(10)     NOT NULL                        COMMENT '회원 ID',
    MEMBER_NAME     VARCHAR(100)    NOT NULL                        COMMENT '회원명',
    NICKNAME        VARCHAR(100)                                    COMMENT '닉네임',
    MEMBER_IS_ADMIN TINYINT                                         COMMENT '관리자 여부',
    PRIMARY KEY (MEMBER_NO)
);

--
-- CATEGORY MAIN INFO
--
DROP TABLE IF EXISTS CATEGORY_MAIN;

CREATE TABLE CATEGORY_MAIN COMMENT '메인 카테고리' (
    CATEGORY_ID     INT         NOT NULL    AUTO_INCREMENT  COMMENT '메인 카테고리 ID',
    CATEGORY_NAME   VARCHAR(20)                             COMMENT '메인 카테고리명',
    PRIMARY KEY (CATEGORY_ID)
);

-- CATEGORY_ID / SUB_CATEGORY_ID를 이용하여 데이터 조회하기 위한 INDEX 추가.
CREATE INDEX CATEGORY_MAIN_CATEGORY_NAME ON CATEGORY_MAIN (CATEGORY_NAME);

--
-- CATEGORY SUB INFO
--
DROP TABLE IF EXISTS CATEGORY_SUB;

CREATE TABLE CATEGORY_SUB COMMENT '서브 카테고리' (
    CATEGORY_ID     INT         NOT NULL    AUTO_INCREMENT  COMMENT '서브 카테고리 ID',
    CATEGORY_NAME   VARCHAR(20)                             COMMENT '서브 카테고리명',
    PRIMARY KEY (CATEGORY_ID)
);

--
-- CATEGORY MAPPING INFO
--
DROP TABLE IF EXISTS CATEGORY_MAPPING;

CREATE TABLE CATEGORY_MAPPING COMMENT '카테고리 매핑 정보' (
    MAPPING_NO          INT     NOT NULL    AUTO_INCREMENT  COMMENT 'MAPPING NUMBER',
    CATEGORY_ID         INT     NOT NULL                    COMMENT '메인 카테고리 ID',
    SUB_CATEGORY_ID     INT     NOT NULL                    COMMENT '서브 카테고리 ID',
    PRIMARY KEY (MAPPING_NO)
);

-- CATEGORY_ID / SUB_CATEGORY_ID를 이용하여 데이터 조회하기 위한 INDEX 추가.
CREATE INDEX CATEGORY_MAPPING_CATEGORY_ID ON CATEGORY_MAPPING (CATEGORY_ID);
CREATE INDEX CATEGORY_MAPPING_SUB_CATEGORY_ID ON CATEGORY_MAPPING (SUB_CATEGORY_ID);

--
-- ITEM INFO
--
DROP TABLE IF EXISTS ITEM;

CREATE TABLE ITEM COMMENT '아이템 정보' (
    ITEM_NO         INT             NOT NULL    AUTO_INCREMENT  COMMENT 'ITEM NUMBER',
    CATEGORY_ID     INT             NOT NULL                    COMMENT '서브 카테고리 ID',
    ITEM_NAME       VARCHAR(200)    NOT NULL                    COMMENT 'ITEM명',
    DESCRIPTION     VARCHAR(1000)                               COMMENT 'ITEM 설명',
    PRICE           BIGINT          NOT NULL                    COMMENT 'ITEM 가격',
    BRAND_NAME      VARCHAR(200)    NOT NULL                    COMMENT '브랜드명',
    PRIMARY KEY (ITEM_NO)
    );

-- CATEGORY_ID / ITEM_TYPE 이용하여 데이터 조회하기 위한 INDEX 추가.
CREATE INDEX ITEM_CATEGORY_ID ON ITEM (CATEGORY_ID);